# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "Jackson Wyndow"
tagline: ""
description: "Follow <a href=\"https://micro.blog/JacksonOfTrades\">@JacksonOfTrades on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/JacksonOfTrades\">@JacksonOfTrades on Micro.blog</a>."
baseurl: ""
url: "https://JacksonOfTrades.micro.blog"
markdown: "kramdown"
username: "JacksonOfTrades"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Jackson Wyndow"
name: "Jackson Wyndow"
gravatar_hash: "ea61fa28a4a8b50be3825a264f1f8b21"
avatar: "https://micro.blog/JacksonOfTrades/avatar.jpg"
full_name: "Jackson Wyndow"
bio: ""
twitter_username: "JacksonOfTrades"
github_username: ""
instagram_username: "jwyndow"
paginate: 20
paginate_path: "/page/:num/"
timezone: "Pacific/Tongatapu"
site_id: "1719"